"""Internal logging configuration for the wyby framework.

This module provides basic logging setup for wyby and a convenience
function for game developers to configure logging in their projects.

Caveats:
    - wyby follows the Python library logging convention: a
      ``NullHandler`` is attached to the ``wyby`` root logger (in
      ``__init__.py``) so that library log messages are silently
      discarded unless the application (i.e. the game) explicitly
      configures logging. This means ``import wyby`` alone will never
      produce log output.
    - :func:`configure_logging` is a convenience helper, not a
      requirement. Game developers who already have their own logging
      setup can ignore it entirely and configure the ``wyby`` logger
      through standard :mod:`logging` module APIs.
    - Log output goes to stderr by default (via ``StreamHandler``).
      Terminal games render to stdout via Rich's ``Live`` display, so
      logging to stderr avoids corrupting the game display. If you
      redirect stderr, logs may be lost — consider passing a *filename*
      for production games.
    - The default format includes a timestamp, logger name, level, and
      message. This is intentionally verbose for debugging. Production
      games may want a terser format or structured logging via the
      *fmt* parameter.
    - File logging appends by default (``filemode="a"``). Log files can
      grow indefinitely during long game sessions. The ``.gitignore``
      generated by ``project_init`` already excludes ``*.log`` files,
      but disk usage is the caller's responsibility.
    - Calling :func:`configure_logging` multiple times is safe but
      additive — each call adds another handler to the ``wyby`` logger.
      If you need to reconfigure, remove existing handlers first or
      configure logging through the standard :mod:`logging` APIs.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

# The package-level logger. All wyby modules use
# ``logging.getLogger(__name__)`` which produces child loggers
# (e.g. ``wyby.project_init``) that propagate to this one.
_LIBRARY_LOGGER_NAME = "wyby"

_DEFAULT_FORMAT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"


def setup_null_handler() -> None:
    """Attach a ``NullHandler`` to the ``wyby`` root logger.

    This is called automatically when the ``wyby`` package is imported
    (see ``__init__.py``). It follows the `Python logging best practice
    for libraries <https://docs.python.org/3/howto/logging.html
    #configuring-logging-for-a-library>`_: library code should never
    configure logging beyond adding a ``NullHandler``, leaving all
    policy decisions to the application.
    """
    logging.getLogger(_LIBRARY_LOGGER_NAME).addHandler(logging.NullHandler())


def configure_logging(
    level: int | str = logging.WARNING,
    *,
    fmt: str = _DEFAULT_FORMAT,
    filename: str | Path | None = None,
    filemode: str = "a",
) -> logging.Logger:
    """Configure logging for the ``wyby`` logger hierarchy.

    This is a convenience function for game developers who want basic
    logging output without writing boilerplate ``logging`` setup code.
    It attaches a handler to the ``wyby`` logger so that log messages
    from all wyby modules are emitted.

    For advanced setups (multiple handlers, custom filters, dictConfig),
    use the standard :mod:`logging` module directly.

    Args:
        level: Minimum log level. Accepts standard level names
            (``"DEBUG"``, ``"INFO"``, etc.) or integer constants from
            :mod:`logging`. Defaults to ``WARNING``.
        fmt: Log message format string using %-style placeholders.
            Defaults to a timestamped format suitable for debugging.
        filename: If provided, log to this file instead of stderr.
            Parent directories are **not** created automatically — the
            caller must ensure the directory exists.
        filemode: File open mode when *filename* is set. Defaults to
            ``"a"`` (append). Use ``"w"`` to overwrite on each run.

    Returns:
        The configured ``wyby`` :class:`logging.Logger`.

    Caveats:
        - This function configures the ``wyby`` logger, not the root
          logger. Log messages from other libraries (e.g. Rich, urllib)
          are not affected.
        - When *filename* is ``None``, output goes to stderr. This is
          deliberate: wyby games render to stdout, so logging to stderr
          keeps the game display clean. If your terminal mixes stderr
          into the display, use *filename* instead.
        - Each call adds a new handler. Calling this function twice
          with different settings produces duplicate output. Remove
          handlers manually or call this only once at startup.
    """
    wyby_logger = logging.getLogger(_LIBRARY_LOGGER_NAME)

    if isinstance(level, str):
        level = getattr(logging, level.upper())

    wyby_logger.setLevel(level)

    formatter = logging.Formatter(fmt)

    if filename is not None:
        handler: logging.Handler = logging.FileHandler(
            str(filename), mode=filemode
        )
    else:
        # stderr avoids corrupting Rich's stdout-based terminal output.
        handler = logging.StreamHandler(stream=sys.stderr)

    handler.setLevel(level)
    handler.setFormatter(formatter)
    wyby_logger.addHandler(handler)

    return wyby_logger
